"""add refund items table

Revision ID: 3f919d337e45
Revises: 7441313638dc
Create Date: 2026-10-10 12:01:59.778429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f919d337e45'
down_revision: Union[str, Sequence[str], None] = '7441313638dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refund_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('refund_id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_refund_items_amount_positive'),
    sa.CheckConstraint('quantity > 0', name='ck_refund_items_quantity_positive'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['refund_id'], ['refunds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refund_id', 'order_item_id', name='uq_refund_items_refund_order_item')
    )
    op.create_index(op.f('ix_refund_items_order_item_id'), 'refund_items', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_refund_items_refund_id'), 'refund_items', ['refund_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refund_items_refund_id'), table_name='refund_items')
    op.drop_index(op.f('ix_refund_items_order_item_id'), table_name='refund_items')
    op.drop_table('refund_items')
    # ### end Alembic commands ###
