"""align production schema with models

Revision ID: 7441313638dc
Revises: 0c807d40823c
Create Date: 2026-10-10 10:07:34.543191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7441313638dc'
down_revision: Union[str, Sequence[str], None] = '0c807d40823c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_addresses_id'), table_name='addresses')
    op.create_index(op.f('ix_addresses_user_id'), 'addresses', ['user_id'], unique=False)
    op.drop_constraint(op.f('addresses_user_id_fkey'), 'addresses', type_='foreignkey')
    op.create_foreign_key(None, 'addresses', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('brands', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
              postgresql_using="created_at AT TIME ZONE 'UTC'")
    op.alter_column('brands', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
              postgresql_using="updated_at AT TIME ZONE 'UTC'")
    op.drop_index(op.f('ix_brands_id'), table_name='brands')
    op.drop_index(op.f('ix_cart_items_id'), table_name='cart_items')
    op.drop_constraint(op.f('cart_items_product_id_fkey'), 'cart_items', type_='foreignkey')
    op.drop_constraint(op.f('cart_items_cart_id_fkey'), 'cart_items', type_='foreignkey')
    op.create_foreign_key(None, 'cart_items', 'products', ['product_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'cart_items', 'carts', ['cart_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_carts_id'), table_name='carts')
    op.drop_constraint(op.f('carts_user_id_fkey'), 'carts', type_='foreignkey')
    op.create_foreign_key(None, 'carts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.alter_column('coupon_usages', 'used_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
              postgresql_using="used_at AT TIME ZONE 'UTC'")
    op.drop_index(op.f('ix_coupon_usages_id'), table_name='coupon_usages')
    op.drop_constraint(op.f('coupon_usages_coupon_id_fkey'), 'coupon_usages', type_='foreignkey')
    op.drop_constraint(op.f('coupon_usages_user_id_fkey'), 'coupon_usages', type_='foreignkey')
    op.drop_constraint(op.f('coupon_usages_order_id_fkey'), 'coupon_usages', type_='foreignkey')
    op.create_foreign_key(None, 'coupon_usages', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'coupon_usages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'coupon_usages', 'coupons', ['coupon_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('coupons', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
              postgresql_using="start_date AT TIME ZONE 'UTC'")
    op.alter_column('coupons', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
              postgresql_using="end_date AT TIME ZONE 'UTC'")
    op.drop_index(op.f('ix_coupons_code'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_id'), table_name='coupons')
    op.create_unique_constraint(None, 'coupons', ['code'])
    op.alter_column('discounts', 'value',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('discounts', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
              postgresql_using="start_date AT TIME ZONE 'UTC'")
    op.alter_column('discounts', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
              postgresql_using="end_date AT TIME ZONE 'UTC'")
    op.drop_index(op.f('ix_discounts_id'), table_name='discounts')
    op.create_index(op.f('ix_discounts_product_id'), 'discounts', ['product_id'], unique=False)
    op.drop_constraint(op.f('discounts_product_id_fkey'), 'discounts', type_='foreignkey')
    op.create_foreign_key(None, 'discounts', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_inventory_id'), table_name='inventory')
    op.drop_constraint(op.f('inventory_product_id_fkey'), 'inventory', type_='foreignkey')
    op.create_foreign_key(None, 'inventory', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_constraint(op.f('order_items_product_id_fkey'), 'order_items', type_='foreignkey')
    op.drop_constraint(op.f('order_items_order_id_fkey'), 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'order_items', 'products', ['product_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('order_status_history', 'changed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
              postgresql_using="changed_at AT TIME ZONE 'UTC'")
    op.drop_index(op.f('ix_order_status_history_id'), table_name='order_status_history')
    op.create_index('ix_order_status_history_order_changed', 'order_status_history', ['order_id', 'changed_at'], unique=False)
    op.drop_constraint(op.f('order_status_history_order_id_fkey'), 'order_status_history', type_='foreignkey')
    op.create_foreign_key(None, 'order_status_history', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.alter_column('orders', 'shipping_address_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
              postgresql_using="created_at AT TIME ZONE 'UTC'")
    op.alter_column('orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
              postgresql_using="updated_at AT TIME ZONE 'UTC'")
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.create_index(op.f('ix_orders_shipping_address_id'), 'orders', ['shipping_address_id'], unique=False)
    op.create_index('ix_orders_status_created', 'orders', ['order_status', 'created_at'], unique=False)
    op.create_index('ix_orders_user_created', 'orders', ['user_id', 'created_at'], unique=False)
    op.create_unique_constraint(None, 'orders', ['order_number'])
    op.drop_constraint(op.f('orders_shipping_address_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_user_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'orders', 'addresses', ['shipping_address_id'], ['id'], ondelete='SET NULL')
    op.alter_column('password_reset_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
              postgresql_using="expires_at AT TIME ZONE 'UTC'")
    op.alter_column('password_reset_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
              postgresql_using="created_at AT TIME ZONE 'UTC'")
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.create_unique_constraint(None, 'password_reset_tokens', ['token_hash'])
    op.alter_column('payments', 'paid_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
              postgresql_using="paid_at AT TIME ZONE 'UTC'")
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
              postgresql_using="created_at AT TIME ZONE 'UTC'")
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.create_index('ix_payments_status_created_at', 'payments', ['status', 'created_at'], unique=False)
    op.drop_constraint(op.f('payments_order_id_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'orders', ['order_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('product_images', 'image_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=2048),
               existing_nullable=False)
    op.drop_index(op.f('ix_product_images_id'), table_name='product_images')
    op.drop_constraint(op.f('product_images_product_id_fkey'), 'product_images', type_='foreignkey')
    op.create_foreign_key(None, 'product_images', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.alter_column('products', 'rating',
               existing_type=sa.NUMERIC(precision=2, scale=1),
               type_=sa.Numeric(precision=3, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.create_index('ix_products_active_created', 'products', ['is_active', 'created_at'], unique=False)
    op.create_index('ix_products_category_active', 'products', ['category_id', 'is_active'], unique=False)
    op.drop_constraint(op.f('products_category_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('refunds', 'reason',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('refunds', 'requested_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
              postgresql_using="requested_at AT TIME ZONE 'UTC'")
    op.alter_column('refunds', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
              postgresql_using="completed_at AT TIME ZONE 'UTC'")
    op.drop_index(op.f('ix_refunds_id'), table_name='refunds')
    op.create_index(op.f('ix_refunds_order_id'), 'refunds', ['order_id'], unique=False)
    op.create_index(op.f('ix_refunds_payment_id'), 'refunds', ['payment_id'], unique=False)
    op.create_index('ix_refunds_status_requested_at', 'refunds', ['status', 'requested_at'], unique=False)
    op.execute("DROP INDEX IF EXISTS uq_refunds_one_active_per_order")
    op.create_index('uq_refunds_one_active_per_order', 'refunds', ['order_id'], unique=True, postgresql_where=sa.text("status IN ('requested', 'approved', 'processing', 'completed')"), sqlite_where=sa.text("status IN ('requested', 'approved', 'processing', 'completed')"))
    op.drop_constraint(op.f('refunds_order_id_fkey'), 'refunds', type_='foreignkey')
    op.drop_constraint(op.f('refunds_payment_id_fkey'), 'refunds', type_='foreignkey')
    op.create_foreign_key(None, 'refunds', 'orders', ['order_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'refunds', 'payments', ['payment_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('reviews', 'comment',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2000),
               existing_nullable=True)
    op.alter_column('reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
              postgresql_using="created_at AT TIME ZONE 'UTC'")
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.create_index('ix_reviews_product_status_created', 'reviews', ['product_id', 'status', 'created_at'], unique=False)
    op.create_index('ix_reviews_status_created', 'reviews', ['status', 'created_at'], unique=False)
    op.drop_constraint(op.f('reviews_user_id_fkey'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('reviews_product_id_fkey'), 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reviews', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('site_settings', 'navbar_logo_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=2048),
               existing_nullable=True)
    op.alter_column('site_settings', 'hero_image_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=2048),
               existing_nullable=True)
    op.alter_column('site_settings', 'footer_logo_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=2048),
               existing_nullable=True)
    op.alter_column('site_settings', 'favicon_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=2048),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
              postgresql_using="created_at AT TIME ZONE 'UTC'")
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
              postgresql_using="updated_at AT TIME ZONE 'UTC'")
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.create_unique_constraint(None, 'users', ['phone_number'])
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_index(op.f('ix_wishlist_items_id'), table_name='wishlist_items')
    op.create_index(op.f('ix_wishlist_items_product_id'), 'wishlist_items', ['product_id'], unique=False)
    op.create_index('ix_wishlist_items_user_created', 'wishlist_items', ['user_id', 'created_at'], unique=False)
    op.drop_constraint(op.f('wishlist_items_user_id_fkey'), 'wishlist_items', type_='foreignkey')
    op.drop_constraint(op.f('wishlist_items_product_id_fkey'), 'wishlist_items', type_='foreignkey')
    op.create_foreign_key(None, 'wishlist_items', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'wishlist_items', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Automatic downgrade is disabled for this production migration."""
    raise RuntimeError(
        "Automatic downgrade is disabled for this production migration."
    )
