import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import api from "../services/api";
import ProductCard from "../components/ProductCard";
import { CategoryCard, EmptyState, LoadingState, PageIntro } from "../components/Storefront";

export function CategoryPage(){const {slug}=useParams();const [data,setData]=useState({products:[],category:null,images:{}});const [loading,setLoading]=useState(true);const [error,setError]=useState("");useEffect(()=>{let alive=true;Promise.all([api.get("/categories/"),api.get("/products/")]).then(async ([c,p])=>{const category=c.data.find(x=>x.slug===slug);if(!category)throw new Error("Category not found");const products=p.data.filter(x=>x.category_id===category.id);const images=await Promise.all(products.map(async x=>{try{const r=await api.get(`/products/${x.id}/images`);return[x.id,r.data.find(i=>i.is_primary)?.image_url||r.data[0]?.image_url]}catch{return[x.id,null]}}));if(alive)setData({category,products,images:Object.fromEntries(images.filter(([,v])=>v))})}).catch(e=>alive&&setError(e.message==="Category not found"?"This collection could not be found.":"We couldn’t load this collection.")).finally(()=>alive&&setLoading(false));return()=>{alive=false}},[slug]);return <div className="mx-auto max-w-7xl px-6 py-10"><div className="mb-5 text-xs text-[#737A74]"><Link to="/">Home</Link><span className="mx-2">/</span><Link to="/categories">Categories</Link>{data.category&&<><span className="mx-2">/</span>{data.category.name}</>}</div>{loading?<LoadingState label="Preparing this collection…"/>:error?<EmptyState title="Collection unavailable" text={error} action="Browse all categories" to="/categories"/>:<><div className="mb-10 rounded-3xl bg-[#E2E9E1] px-7 py-10 md:px-12"><p className="eyebrow">TerraLens collection</p><h1 className="mt-3 text-3xl font-semibold">{data.category.name}</h1><p className="mt-3 max-w-xl text-sm leading-6 text-[#657067]">A considered selection from the TerraLens collection.</p></div><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-semibold">{data.products.length} {data.products.length===1?"product":"products"}</h2><Link to="/shop" className="text-sm text-[#486B57]">All products →</Link></div>{data.products.length?<div className="grid grid-cols-2 gap-4 sm:grid-cols-2 lg:grid-cols-4">{data.products.map(p=><ProductCard key={p.id} product={p} imageUrl={data.images[p.id]}/>)}</div>:<EmptyState title="Nothing in this collection yet" text="Try another category or explore the full shop." action="Browse the shop"/>}</>}</div>}
function Categories(){const[categories,setCategories]=useState([]);const[loading,setLoading]=useState(true);const[error,setError]=useState(false);useEffect(()=>{api.get("/categories/").then(r=>setCategories(r.data)).catch(()=>setError(true)).finally(()=>setLoading(false))},[]);return <div className="mx-auto max-w-7xl px-6 py-12"><PageIntro eyebrow="Find your kind of thing" title="All Categories" description="Browse the TerraLens collection by category."/>{loading?<LoadingState/>:error?<EmptyState title="Couldn’t load categories" text="Please try again in a moment."/>:categories.length?<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{categories.map(c=><CategoryCard key={c.id} category={c}/>)}</div>:<EmptyState title="No categories yet" text="Check back as our collection grows." action="Shop all products"/>}</div>}
export default Categories;
